### ISSUE TITLE
NullPointerException is thrown when an object has a member of the same class

### ISSUE THREAD

**Issue by ghost** [jcazevedo/moultingyaml#32]
When serializing an object which has a member of the same class a NullPointerException is thrown.
I'm using version 0.4.0
Following are the exception's stack trace and the source code to reproduce.

```
Exception in thread "main" java.lang.NullPointerException
	at net.jcazevedo.moultingyaml.package$PimpedAny$.toYaml$extension(package.scala:59)
	at net.jcazevedo.moultingyaml.StandardFormats$$anon$1.write(StandardFormats.scala:14)
	at net.jcazevedo.moultingyaml.StandardFormats$$anon$1.write(StandardFormats.scala:11)
	at net.jcazevedo.moultingyaml.package$PimpedAny$.toYaml$extension(package.scala:59)
	at net.jcazevedo.moultingyaml.ProductFormats.writeField(ProductFormats.scala:1064)
	at net.jcazevedo.moultingyaml.ProductFormats.writeField$(ProductFormats.scala:1058)
	at demo.scala.YamlProtocol$.writeField(ScalaMain.scala:6)
	at net.jcazevedo.moultingyaml.ProductFormats$$anon$21.write(ProductFormats.scala:211)
	at net.jcazevedo.moultingyaml.ProductFormats$$anon$21.write(ProductFormats.scala:205)
	at net.jcazevedo.moultingyaml.package$PimpedAny$.toYaml$extension(package.scala:59)
	at demo.scala.ScalaMain$.delayedEndpoint$demo$scala$ScalaMain$1(ScalaMain.scala:16)
	at demo.scala.ScalaMain$delayedInit$body.apply(ScalaMain.scala:10)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at demo.scala.ScalaMain$.main(ScalaMain.scala:10)
	at demo.scala.ScalaMain.main(ScalaMain.scala)
```

```
package demo.scala
import net.jcazevedo.moultingyaml._

case class A(i: Int, s: String, a: Option[A] = None)

object YamlProtocol extends DefaultYamlProtocol {
  implicit val formatA: YamlFormat[A] = yamlFormat3(A)
}

object ScalaMain extends App {
  import YamlProtocol._

  val a = A(1, "foo")
  val b = A(2, "bar", Some(A(3, "foo-bar")))
  a.toYaml.prettyPrint //works fine
  b.toYaml.prettyPrint //NullPointerException
}
```

**Comment by jcazevedo** [comment]
For recursive types, you need to wrap the constructor of your format with `lazyFormat` to avoid running into `NullPointerException`s at runtime:

```scala
implicit val formatA: YamlFormat[A] = lazyFormat(yamlFormat3(A))
```

Unfortunately this isn't documented yet. MoultingYAML's design was heavily inspired by [spray-json](https://github.com/spray/spray-json)'s, so most of the time you can look at their [documentation](https://github.com/spray/spray-json#jsonformats-for-recursive-types) for pointers.

**Comment by ghost** [comment]
Thank you very much!
